# Generated by Django 4.1.6 on 2023-02-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Клиент'), ('TECHNICIAN', 'Техник'), ('MANAGER', 'Менеджер'), ('DIRECTOR', 'Директор')], default='CUSTOMER', max_length=15),
        ),
    ]
