# Generated by Django 4.1.6 on 2023-02-03 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Адресс')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('to_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Аренда')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='TypesService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WITHDRAWAL', 'Снятие кассы')], default='WITHDRAWAL', max_length=11, verbose_name='Вид обслуживания')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание заявки')),
                ('status', models.CharField(choices=[('CREATED', 'Новая заявка от клиента'), ('CONFIRMED', 'Подтверждена техником'), ('READY_TO_WORK', 'Готова к работе'), ('PROGRESS', 'В работе'), ('VERIFICATION', 'Ремонт выполнен'), ('TESTS', 'На тестировании'), ('RE_REPAIR', 'На доработку')], max_length=20)),
                ('time_to_device', models.DateTimeField(blank=True, null=True, verbose_name='Время обслуживаня')),
                ('address_to_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='device.address', verbose_name='Адрес')),
                ('type_of_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_service', to='device.typesservice', verbose_name='Тип обслуживания')),
                ('users', models.ManyToManyField(related_name='service', to=settings.AUTH_USER_MODEL, verbose_name='Учасники заявки')),
            ],
        ),
    ]
