# Generated by Django 4.1.6 on 2023-02-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='address',
            name='house',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='дом'),
        ),
        migrations.AddField(
            model_name='address',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='организация'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='улица'),
        ),
    ]
