# Generated by Django 4.1.6 on 2023-02-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_address_city_address_house_address_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(default='', max_length=100, verbose_name='дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(default='', max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='улица'),
        ),
    ]
