# Generated by Django 4.1.6 on 2023-02-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_address_city_alter_address_house_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
    ]
